spring.jackson.serialization.indent_output=true
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss.SSSZ
spring.jackson.default-property-inclusion=non_null

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always
